export const SELECT_BEAD = 'SELECT_BEAD';
export const SELECT_PAINT_MODE = 'SELECT_PAINT_MODE';
export const UPDATE_NECKLACE_PATTERN = 'UPDATE_NECKLACE_PATTERN';

export const FETCH_STUFF = 'FETCH_STUFF';
export const RECEIVE_STUFF = 'RECEIVE_STUFF';